# Generated by Django 5.0 on 2026-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('study_type', models.CharField(max_length=100)),
                ('study_date', models.DateField()),
                ('study_time', models.TimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
