# Generated by Django 4.2.11 on 2026-02-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_patientstudy_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('confidence_level', models.CharField(max_length=50)),
                ('finding_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('observation', models.TextField()),
                ('severity', models.CharField(max_length=100)),
                ('impression', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
