# Generated by Django 5.0 on 2026-03-12 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='patient_name',
            field=models.CharField(default='Unknown Patient', max_length=255),
        ),
        migrations.AddField(
            model_name='aireport',
            name='scan_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
