# Generated by Django 5.0 on 2026-03-17 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aireport_patient_name_aireport_scan_image_otpmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='scans/')),
                ('scan_type', models.CharField(blank=True, choices=[('CT', 'CT Scan'), ('MRI', 'MRI Scan'), ('XRAY', 'X-Ray')], max_length=10, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='api.user'),
        ),
    ]
