# Generated by Django 5.0 on 2026-03-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_scanprediction_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
