# Generated by Django 5.0 on 2026-03-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_aichat'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
