# Generated by Django 5.0 on 2026-03-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_patient_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='country_code',
        ),
    ]
